name: Release

on: 
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      FILE_NAME: brain_manager
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macOS-latest,windows-latest,macOS-13]

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: release
      run: cargo build --release

    - name: 'Tar files'
      run: tar -cvf ${{ matrix.os }}-${{ env.FILE_NAME }}.tar ./target/release
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ env.FILE_NAME }}
        path: ${{ matrix.os }}-${{ env.FILE_NAME }}.tar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-latest,macOS-latest,windows-latest,macOS-13]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          artifacts: './${{ matrix.os }}-${{ env.FILE_NAME }}/${{ matrix.os }}-${{ env.FILE_NAME }}.tar'